name: ai_music_production_platform

description: A Flutter app for AI Music Production.

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.0
  audioplayers: ^0.20.1
  path_provider: ^2.0.11
  # Include any additional necessary dependencies

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  # Add any dev dependencies if required

# Flutter configuration
flutter:
  uses-material-design: true
  assets:
    - assets/  # Assets directory for the app
